### ISSUE TITLE
Make sure mail sender is working

### ISSUE THREAD

**Issue by alambaDev** [kartoza/SAEOSS-Portal#341]

**Comment by Indiphile** [comment]
Open an issue [here on SANSA-EO](https://github.com/SANSA-EO/SAEOSS-PORTAL/issues)

**Comment by osundwajeff** [comment]
Command: `ckan saeoss send-email-notifications`
Been getting this error:
```Traceback (most recent call last):
  File "/home/appuser/.local/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 1081, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 949, in make_context
    self.parse_args(ctx, args)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/cli/cli.py", line 120, in parse_args
    result = super().parse_args(ctx, args)
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 1653, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 1417, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 2403, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/appuser/.local/lib/python3.9/site-packages/click/core.py", line 2365, in process_value
    value = self.callback(ctx, self, value)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/cli/cli.py", line 130, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/cli/cli.py", line 139, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/cli/cli.py", line 56, in __init__
    self.app = make_app(raw_config)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/config/middleware/__init__.py", line 29, in make_app
    load_environment(conf)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/config/environment.py", line 68, in load_environment
    p.load_all()
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/plugins/core.py", line 148, in load_all
    load(*plugins)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/plugins/core.py", line 164, in load
    service = _get_service(plugin)
  File "/home/appuser/.local/lib/python3.9/site-packages/ckan/plugins/core.py", line 285, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.base.PluginNotFoundException: Interface harvest does not exist```

**Comment by voogt** [comment]
Thanks @osundwajeff I will take look at it

**Comment by osundwajeff** [comment]
Hi @voogt I did not. I just kept getting issues on the interfaces

**Comment by voogt** [comment]
hi @osundwajeff please try setting the smtp settings and trying again. I have not gotten the errors you specified

**Comment by alambaDev** [comment]
This issue has been solved
